### ISSUE TITLE
Please tag

### ISSUE THREAD

**Issue by mschauer** [JuliaDSP/Wavelets.jl#45]
Ref https://discourse.julialang.org/t/package-compatibility-caps/15301

and

https://github.com/JuliaRegistries/General/tree/master/W/Wavelets

**Comment by tknopp** [comment]
ping @gummif this package is unfortunately not installable anymore due to capping.

**Comment by ararslan** [comment]
I haven't done much maintenance of this package, but given the circumstances and that tests are passing on all versions, I went ahead and tagged v0.8.0. (Note that it's a minor release rather than a patch because new features were introduced.) I reviewed the changes since the last release and they look good to me.

See https://github.com/JuliaLang/METADATA.jl/pull/18477
